export const metadata = { title: "Team Augmentation | Byte Innovations", description: "Scale your team with vetted professionals who integrate with your workflow." };

const asset = (file) => `/images/team-augmentation-figma/${file}`;
const benefits = ["Reduce hiring time", "Scale teams based on business demand", "Access specialized expertise on demand", "Lower recruitment and operational costs", "Eliminate payroll and HR administration", "Improve workforce flexibility", "Accelerate project delivery", "Reduce hiring risks"];
const process = [["Requirement Discovery", "We begin by understanding your business objectives, technical requirements, organizational culture, project scope, and hiring expectations."], ["Talent Identification", "Our recruitment specialists source, evaluate, and shortlist candidates from our extensive talent network and recruitment ecosystem."], ["Assessment & Validation", "Candidates undergo structured interviews, technical evaluations, behavioral assessments, and reference verification to ensure they meet both technical and cultural expectations."], ["Client Interview", "You interview shortlisted candidates and select the professionals who best fit your organization."], ["Deployment", "Selected professionals are onboarded and begin working directly with your team while remaining employed by Byte Innovations."], ["Ongoing Workforce Management", "We continue managing payroll, HR support, compliance, employee engagement, attendance, leave, performance reviews, and workforce administration throughout the engagement."]];
const engagement = [["Dedicated Resource", "A full-time professional working exclusively with your organization.", "Ideal for long-term business operations and continuous product development."], ["Dedicated Team", "A complete cross-functional team assembled specifically for your business.", "Ideal for product development, enterprise transformation, and managed delivery."], ["Project-Based Augmentation", "Professionals assigned for specific projects or defined business initiatives.", "Ideal for temporary capacity expansion."], ["Contract-to-Hire", "Evaluate professionals within your business before making permanent hiring decisions.", "Ideal for organizations planning long-term workforce expansion."]];
const professionals = [
  ["Technology", ["Full Stack Developers", "Backend Developers", "Mobile App Developers", "QA Engineers", "DevOps Engineers", "UI/UX Designers", "Solution Architects", "AI & Machine Learning Engineers", "Data Engineers", "Cybersecurity Specialists", "Cloud Engineers", "Fractional CTO"]],
  ["Product & Project", ["Product Managers", "Project Managers", "Scrum Masters", "Business Analysts", "Product Designers"]],
  ["Business Operations", ["Business Development Professionals", "Sales Professionals", "Customer Success Executives", "Digital Marketing Specialists", "SEO Specialists", "Content Writers"]],
  ["Corporate Functions", ["HR Professionals", "Administrative Professionals", "Finance & Accounts Professionals", "Legal Practitioners", "Procurement Specialists", "Operations Executives"]],
];
const industries = ["Software & Technology", "FinTech", "Healthcare", "Retail", "Manufacturing", "Logistics", "Education", "Travel & Hospitality", "Government & NGOs", "E-commerce", "Professional Services", "Telecommunications"];
const faqs = ["How quickly can resources be deployed?", "Who manages the employees?", "Can I scale my team later?", "Where does BI operate, and whom can they work with?", "What happens if a resource isn't the right fit?", "Can I hire both technical and non-technical professionals?"];
function Button({ children }) { return <a className="primary-button ta-button" href="/#contact">{children}</a>; }
function Heading({ eyebrow, title, text, center = false }) { return <div className={`ta-heading${center ? " is-center" : ""}`}><p>{eyebrow}</p><h2>{title}</h2>{text ? <span>{text}</span> : null}</div>; }
function ProfessionalCard({ group, className = "", device = false }) { const [title, list] = group; return <article className={`ta-professional-card ${className}`}><h3>{title}</h3><ul>{list.map((item) => <li key={item}>✓ <span>{item}</span></li>)}</ul>{device ? <img className="ta-professional-device" src={asset("raw-10.png")} alt="" /> : null}</article>; }

export default function TeamAugmentationPage() {
  return <main className="ta-page">
    <section className="ta-hero"><div className="site-container ta-hero-grid"><div><Heading eyebrow="Team Augmentation" title={<>What is Team<br />Augmentation?</>} text="Hiring the right talent is one of the biggest challenges growing businesses face. Recruitment delays, administrative overhead, employee management, and fluctuating workloads often slow down business growth." /><p className="ta-hero-extra">Team Augmentation enables organizations to quickly extend their workforce with dedicated professionals who work as an extension of their internal teams. Unlike traditional outsourcing, augmented professionals collaborate directly with your managers, follow your processes, and become part of your day-to-day operations while remaining full-time employees of Byte Innovations.</p><p className="ta-hero-extra">This model allows you to increase capacity, access specialized expertise, reduce hiring risks, and maintain complete operational control without expanding your internal HR and administrative responsibilities.</p><Button>Build Your Team</Button></div><img src={asset("raw-07.png")} alt="Byte Innovations team working together" /></div></section>
    <section className="ta-pink"><div className="site-container"><Heading center eyebrow="Build the Right Product Before Building the Product Right." title="Why Businesses Choose Team Augmentation?" text={<>Modern businesses require flexibility.<br /><br />Instead of spending months recruiting, onboarding, and managing employment administration, organizations can immediately access qualified professionals who are ready to contribute from day one.<br /><br /><strong>Our Team Augmentation model helps organizations</strong></>} /><div className="ta-benefits">{benefits.map((benefit, index) => <article key={benefit}><img src={asset(`raw-${String(20 + (index % 9)).padStart(2, "0")}.svg`)} alt="" /><p>{benefit}</p></article>)}</div></div></section>
    <section className="ta-why"><div className="site-container"><Heading center eyebrow="More Than Staffing. A Strategic Workforce Partner." title="Why Byte Innovations?" text={<>At Byte Innovations, we don&apos;t simply provide professionals—we build long-term workforce partnerships.<br /><br />Every resource we deploy goes through structured recruitment, technical or functional evaluation, background verification, and continuous performance management to ensure consistent quality throughout the engagement.<br /><br />Unlike conventional staffing providers, we remain actively involved even after deployment by managing HR operations, employee engagement, compliance, payroll administration, leave management, and performance reviews.<br /><br />This allows your managers to focus entirely on business outcomes while we take care of workforce operations.</>} /><div className="ta-value-grid">{["Carefully screened professionals", "Fast deployment process", "Flexible engagement models", "Dedicated Account Manager", "Continuous HR Support", "Payroll & Compliance Management", "Performance Monitoring", "Replacement Guarantee", "Scalable Workforce Solutions"].map((label, index) => <article className={`ta-value ta-value--${index + 1}`} key={label}><b><img src={asset(`raw-${String(20 + index).padStart(2, "0")}.svg`)} alt="" /></b><p>{label}</p></article>)}</div></div></section>
    <section className="ta-process"><div className="site-container"><Heading center eyebrow="A Simple Process Designed for Speed and Quality" title="Our Team Augmentation Process" /><div className="ta-process-grid"><div>{process.slice(0, 3).map(([title, text], index) => <article key={title}><b>{index + 1}</b><h3>{title}</h3><p>{text}</p></article>)}</div><img src={asset("raw-08.png")} alt="Team augmentation specialists" /><div>{process.slice(3).map(([title, text], index) => <article key={title}><b>{index + 4}</b><h3>{title}</h3><p>{text}</p></article>)}</div></div></div></section>
    <section className="ta-blue"><div className="site-container"><Heading eyebrow="Ways to work with us" title="Engagement Models" text="Every business has different workforce requirements. We offer flexible engagement models to match your operational needs." /><div className="ta-engagement">{engagement.map(([title, text, ideal], index) => <article className={`ta-engagement-card ta-engagement-card--${index + 1}`} key={title}><div className="ta-engagement-image"><img src={asset("raw-09.png")} alt="" /></div><h3>{title}</h3><p>{text}<br /><br />{ideal}</p></article>)}</div></div></section>
    <section className="ta-pink ta-professionals"><div className="site-container"><Heading center eyebrow="Our Professionals" title="Professionals You Can Hire" text="Our talent network includes professionals across technology, business, operations, and corporate functions." /><div className="ta-professional-grid"><ProfessionalCard group={professionals[0]} className="ta-professional-card--technology" device /><div className="ta-professional-stack"><ProfessionalCard group={professionals[1]} /><ProfessionalCard group={professionals[2]} /></div><div className="ta-professional-stack"><img className="ta-professional-photo" src={asset("raw-11.png")} alt="Team augmentation professional" /><ProfessionalCard group={professionals[3]} /></div></div></div></section>
    <section className="ta-industries"><div className="site-container"><Heading center eyebrow="Industries" title="Industries We Support" text="Our professionals have experience supporting organizations across multiple industries." /><div className="ta-industries-grid">{industries.map((industry, index) => <article key={industry}><img src={asset(`raw-${String(34 + (index % 11)).padStart(2, "0")}.svg`)} alt="" /><span>{industry}</span></article>)}</div></div></section>
    <section className="ta-faq"><div className="site-container ta-faq-grid"><Heading eyebrow="FAQ" title={<>Everything<br /><em>You Need to Know</em></>} /> <div>{faqs.map((question) => <details key={question}><summary>{question}<span>+</span></summary></details>)}</div></div></section>
    <section className="ta-ready"><div className="site-container"><Heading center eyebrow="Contact us" title="Ready to Scale Your Team?" text={<>Whether you&apos;re building a product, expanding operations, or filling critical skill gaps, Byte Innovations provides the professionals you need—quickly, reliably, and without the complexity of traditional hiring.<br /><br />From recruitment and deployment to payroll, compliance, and ongoing workforce management, we become your trusted workforce partner so your team can stay focused on delivering results.<br /><br /><strong>Let&apos;s build your team—faster, smarter, and with confidence.</strong></>} /><div className="ta-centered"><Button>Let&apos;s Build Together</Button></div><div className="ta-collage"><div><img src={asset("raw-12.png")} alt="" /><img src={asset("raw-13.png")} alt="Team member at whiteboard" /></div><img src={asset("raw-14.png")} alt="Byte Innovations team" /><div><img src={asset("raw-15.png")} alt="Byte Innovations office" /><img src={asset("raw-12.png")} alt="" /></div></div></div></section>
  </main>;
}
