export const metadata = { title: "MVP Calculator | Byte Innovations", description: "Estimate your MVP scope, timeline, and build cost with Byte Innovations." };

const audience = ["Startup founders and entrepreneurs", "UI/UX teams planning early product flows", "Product managers and product owners", "Software development teams preparing project scopes", "Business owners planning a new digital product", "Business analysts and strategy teams", "CTOs and technical decision-makers", "Incubators and accelerators supporting startups", "Investors evaluating startup feasibility", "Freelancers or agencies preparing MVP proposals"];
const steps = [
  ["Define Your MVP Type and Scope", "First, you select the type of MVP you want to build. This may include a web application, mobile application, SaaS platform, marketplace, dashboard, automation system, or AI-powered product. You also define the core scope, such as target users, major modules, platforms, and business goals."],
  ["Assess Feature Complexity", "Every feature has a different level of effort. A simple login system may take less time, while role-based access, payment gateways, dashboards, reporting, or AI-based features may require deeper planning and development."],
  ["Choose the Technology Stack", "The technology stack also affects development time, scalability, and cost. Depending on the product type, Byte Innovations may recommend technologies such as React, Next.js, Laravel, Node.js, Django, Flutter, React Native, or other suitable frameworks."],
  ["Include UI/UX Design Requirements", "A strong MVP should not only work, but also feel simple and usable. The calculator considers whether your product needs basic wireframes, standard UI design, custom user flows, dashboards, mobile-responsive layouts, or advanced product experience design."],
  ["Add Integrations and Testing", "Many MVPs need third-party integrations such as payment gateways, SMS or email services, CRM, analytics tools, APIs, maps, authentication systems, or AI services. Each integration adds development and testing effort."],
  ["Generate a Cost Breakdown", "After collecting the inputs, the calculator provides an estimated cost range based on features, design, development, testing, and delivery phases. This gives you a practical budget direction and helps you decide whether to proceed with the full MVP scope or reduce the first release."],
];
const factors = [
  ["Project Complexity", "The more complex the product, the higher the development cost. A basic landing page or simple feature tool requires less effort, while a SaaS platform, marketplace, ERP module, AI product, or multi-user dashboard requires more planning, development, and testing."],
  ["Scope of Core Features", "MVP cost depends heavily on how many features you include in the first version. The best approach is to focus only on the features that are necessary to validate the product idea."],
  ["Platform Type", "A web-only MVP usually costs less than a product that requires both web and mobile apps. Native mobile apps for Android and iOS may also cost more than cross-platform development."],
  ["UI/UX Design Level", "Basic designs are faster to prepare. However, if your MVP needs custom branding, detailed user journeys, interactive dashboards, or advanced mobile experience, the design cost and timeline will increase."],
  ["Development Team Structure", "A typical MVP team may include a project manager, UI/UX designer, frontend developer, backend developer, QA engineer, and technical lead. The cost depends on team size, experience level, and project duration."],
  ["Testing and Improvement Cycles", "Testing is critical for MVP development. Even after launch, improvements may be needed based on user feedback. This is why it is smart to keep a budget buffer for bug fixing, optimization, and small changes after the first release."],
];
const tiers = [
  ["Simple MVP", "Only the basic features required to test the idea.", "$3,000–$12,000", "1–3 months", ["Landing page", "simple booking system", "basic dashboard", "single-purpose web app"], "Small team of 2–3 members"],
  ["Mid-Level MVP", "Multiple user roles, custom UI/UX, backend logic, admin panel, and selected integrations.", "$10,000–$50,000", "1–3 months", ["Marketplace", "booking platform", "e-commerce system", "SaaS dashboard, customer portal"], "Cross-functional team with designers, developers, QA, and a project manager"],
  ["Complex MVP", "Advanced workflows, custom backend, multi-platform support, real-time features, AI/ML components, analytics, or multiple integrations.", "$50,000–$150,000+", "1–3 months", ["Landing page", "simple booking system", "basic dashboard", "single-purpose web app"], "A team of 3–6 members"],
];
const reduceCost = ["Prioritizing must-have features only", "Working with an experienced team", "Avoiding unnecessary features in phase one", "Starting with web or cross-platform dev", "Choosing a suitable technology stack", "Keeping the design clean and practical", "Using reusable components", "Validating the idea before scaling"];
const benefits = ["Reduce development costs", "Launch faster", "Validate product-market fit", "Collect real user feedback", "Improve features based on actual demand", "Avoid overbuilding", "Reduce business risk", "Plan future development more clearly"];
const mistakes = [["Underestimating technical complexity", "Complex features and integrations almost always take longer than expected"], ["Ignoring post-launch costs", "Maintenance, bug fixes, updates, and user support are ongoing expenses"], ["Overlooking hidden costs", "Legal compliance, security audits, and compatibility testing can add 10–20% to your budget"], ["Feature overloading in Phase 1", "Too many features confuse users and inflate costs unnecessarily"], ["Mismatched teams", "Inexperienced or poorly coordinated developers slow progress and increase rework"], ["Poor stakeholder communication", "Misaligned expectations lead to scope changes, rework, and cost overruns"]];
const reduceIcons = ["raw-06.png", "raw-17.png", "raw-04.png", "raw-18.png", "raw-14.png", "raw-10.png", "raw-16.png", "raw-12.png"];

function Heading({ eyebrow, title, children, inverse = false, className = "" }) { return <div className={`calculator-section-heading ${inverse ? "is-inverse" : ""} ${className}`}><p>{eyebrow}</p><h2>{title}</h2>{children ? <span>{children}</span> : null}</div>; }
function Factor({ index, title, text }) { return <article><b>{index}</b><h3>{title}</h3><p>{text}</p></article>; }

export default function MvpCalculatorPage() {
  return <main className="calculator-page">
    <section className="calculator-hero"><div className="site-container calculator-hero-layout"><div><p className="calculator-kicker">MVP Calculator</p><h1>What Is an MVP Cost Calculator?</h1><p>An MVP, or Minimum Viable Product, is the first functional version of a digital product built with only the most essential features. The goal is simple: launch faster, test the idea with real users, collect feedback, and avoid spending heavily on features that may not be needed.</p><p>An MVP Cost Calculator helps founders, startups, and businesses estimate the approximate budget required to build this initial version. It considers key factors such as feature complexity, platform type, integrations, design needs, development requirements, testing, and team involvement.</p><p>At Byte Innovations, our MVP Cost Calculator is designed to give you a practical starting point before full-scale development. It helps you understand your possible investment, prioritize must-have features, and plan your product roadmap more confidently.</p><a className="primary-button calculator-cta" href="#calculator-process">Build your MVP</a></div><div className="calculator-visual"><img src="/images/mvp-figma/raw-03.png" alt="MVP calculator" /></div></div></section>
    <section className="calculator-pink-section calculator-audience"><div className="site-container"><Heading eyebrow="Take a look at who we help" title="Who Can Benefit from an MVP Cost Estimator?" /><div className="audience-grid">{audience.map((item, index) => <article key={item}><b>{["▣", "▱", "♧", "⌑", "▤", "◎", "‹›", "⌁", "$", "♙"][index]}</b>{item}</article>)}</div></div></section>
    <section className="calculator-pink-section calculator-process" id="calculator-process"><div className="site-container"><Heading className="is-left" eyebrow="How to use the MVP calculator" title="How Does Our MVP Calculator Work?">Our MVP Calculator follows a structured process to estimate your MVP development cost based on your product idea, required features, technology preferences, and expected launch scope.</Heading><div className="calculator-step-grid">{steps.map(([title, text], index) => <article className={index === 2 || index === 3 ? "is-featured" : index === 1 || index === 5 ? "is-grey" : ""} key={title}><div className="step-number"><b>{index + 1}</b><i /></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="calculator-factors"><div className="site-container"><Heading eyebrow="Factors" title="What Factors Influence the Cost of Building an MVP?" /><div className="factor-layout"><div className="factor-grid">{factors.slice(0, 3).map(([title, text], index) => <Factor key={title} index={index + 1} title={title} text={text} />)}</div><img className="factor-image" src="/images/mvp-figma/raw-05.png" alt="MVP cost planning" /><div className="factor-grid">{factors.slice(3).map(([title, text], index) => <Factor key={title} index={index + 4} title={title} text={text} />)}</div></div></div></section>
    <section className="calculator-cost-section"><div className="site-container"><Heading eyebrow="Cost" title="How Much Does an MVP Typically Cost?" inverse>MVP cost depends on product complexity, features, design, technology, and timeline. However, most MVPs can be grouped into three broad categories.</Heading><div className="cost-tier-grid">{tiers.map(([name, summary, cost, timeline, examples, team]) => <article key={name}><h3>{name}</h3><p className="tier-summary">{summary}</p><p className="tier-label">Estimated cost</p><p className="cost-price">{cost}</p><hr /><p className="tier-label">Estimated timeline</p><p className="cost-duration">{timeline}</p><hr /><p className="tier-label">Examples</p><ul>{examples.map((item) => <li key={item}>{item}</li>)}</ul><hr /><p className="tier-team">{team}</p></article>)}</div></div></section>
    <section className="calculator-pink-section calculator-reduce"><div className="site-container"><Heading eyebrow="Reduce cost" title={<>How Can You Reduce MVP Development Cost Without<br />Compromising Quality?</>}>The best way to reduce MVP cost is to build lean. That means focusing only on the features that solve the main user problem.</Heading><p className="reduce-label">You can reduce cost by:</p><div className="reduce-grid">{reduceCost.map((item, index) => <article key={item}><span>{item}</span><img src={`/images/mvp-figma/${reduceIcons[index]}`} alt="" /></article>)}</div></div></section>
    <section className="calculator-benefits"><div className="site-container"><Heading eyebrow="Benefits of MVP" title={<>What Are the Benefits of a Lean MVP Development<br /><span>Approach?</span></>}>A lean MVP helps you move from idea to market faster. Instead of building a full product based on assumptions, you launch the most important version first and learn from real users.<br /><br />For startups and growing businesses, a lean MVP is often the smartest way to test an idea before making a larger investment.</Heading><p className="approach-label">This approach helps you:</p><div className="benefit-grid">{benefits.map((item, index) => <article className={`benefit-card benefit-card--${index + 1}`} key={item}><span>{item}</span><b>{["$", "◈", "◁", "✦", "▣", "‹›", "◇", "▤"][index]}</b></article>)}</div></div></section>
    <section className="calculator-mistakes"><div className="site-container"><Heading className="is-left" eyebrow="Avoid these" title="Common Mistakes When Estimating MVP Cost">Many businesses make mistakes while estimating MVP cost. These mistakes can increase the budget, delay the launch, or create confusion during development.<br />Avoid these pitfalls that catch many teams off guard</Heading><div className="mistake-grid">{mistakes.map(([title, text], index) => <article key={title}><div className={`mistake-art mistake-art--${index + 1}`} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="calculator-next"><div className="site-container"><Heading eyebrow="What next" title={<>What Should You Do After Calculating<br />Your MVP Cost?</>} inverse>After calculating your MVP cost, review the estimate carefully. Identify which features are essential for launch and which ones can be moved to a later phase.<br /><br />You should also discuss the estimate with a technical team to validate the timeline, development effort, technology stack, and possible risks.<br /><br />The next step is to prepare a clear MVP roadmap with feature priorities, development phases, budget range, and launch plan.</Heading><a className="primary-button calculator-cta" href="/#contact">Book a Call</a></div></section>
    <section className="calculator-help"><div className="site-container"><Heading eyebrow="Let us help" title="How Can Byte Innovations Help?">Byte Innovations helps startups and businesses turn product ideas into scalable digital solutions. From idea validation and UI/UX design to web development, mobile app development, custom software, AI/ML solutions, integrations, testing, and maintenance, we support the full product development journey.<br /><br />Our MVP planning approach helps you understand what to build first, how much it may cost, and how to launch with confidence.<br /><br />Start with a clear estimate. Build only what matters. Launch faster with Byte Innovations.</Heading><a className="primary-button calculator-cta" href="/#contact">Let's Build Together</a><div className="calculator-help-collage"><div className="collage-column collage-column--left"><img src="/images/mvp-figma/raw-19.png" alt="Byte Innovations pattern" /><img src="/images/hero-whiteboard.png" alt="Byte Innovations developers" /></div><img className="collage-team" src="/images/mvp-figma/raw-20.png" alt="Byte Innovations team" /><div className="collage-column collage-column--right"><img src="/images/mvp-figma/raw-07.png" alt="Byte Innovations office" /><img src="/images/mvp-figma/raw-19.png" alt="Byte Innovations pattern" /></div></div></div></section>
  </main>;
}
