export const metadata = { title: "End to End Development | Byte Innovations", description: "Strategy, design, engineering, integration, and support from one accountable software team." };

const qaRows = [["Manual & Functional", "Real user journeys and feature logic validated by hand, not just scripted."], ["Automated & Regression", "Repetitive flows and critical paths automated so nothing breaks silently."], ["API & Performance", "Endpoints, integrations, and load behavior tested before release."]];
const compareRows = ["Business requirement analysis", "Software architecture planning", "Full-cycle custom software development", "API, cloud, and system integration", "QA testing and deployment support", "Long-term maintenance and scaling"];
function Heading({ eyebrow, title, text, center = false }) {
  return <div className={`e2e-heading${center ? " is-center" : ""}`}><p>{eyebrow}</p><h2>{title}</h2>{text ? <span>{text}</span> : null}</div>;
}
function Button({ children }) { return <a className="primary-button e2e-button" href="/#contact">{children}</a>; }

export default function EndToEndDevelopmentPage() {
  return <main className="e2e-page">
    <section className="e2e-hero"><div className="site-container e2e-hero-grid"><div><p className="e2e-eyebrow">End to End&nbsp; Software for modern teams</p><h1>End to End<br />Development Service</h1><p>From first concept to long-term support, we handle every stage of your software&apos;s lifecycle under one roof — strategy, design, engineering, integration, and maintenance — so you get one accountable team instead of a patchwork of vendors.</p><Button>Start a project</Button></div><img src="/images/end-to-end-figma/raw-20.jpeg" alt="Software development team at work" /></div></section>
    <section className="e2e-pink e2e-custom"><div className="site-container"><Heading eyebrow="Build the Right Product Before Building the Product Right." title="Custom Software Development" text="Off-the-shelf tools bend your process to fit their limits. We design and build software from the ground up around your workflows, your data, and your goals — from a single internal tool to a full software system spanning strategy, architecture, and long-term support." /><Button>Build custom software</Button><div className="e2e-three-cards"><article><b>‹›</b><h3>Built around your workflow</h3><p>Software shaped by your processes and users — not a template you have to adapt to.</p></article><article><b>♧</b><h3>Connected, not siloed</h3><p>CRMs, ERPs, APIs, and third-party tools integrated into one working system.</p></article><article><b>▱</b><h3>Built to last</h3><p>Secure, well-architected software that keeps working as your business grows.</p></article></div></div></section>
    <section className="e2e-split"><div className="site-container e2e-split-grid"><img src="/images/end-to-end-figma/raw-06.jpeg" alt="Web application workspace" /><div><Heading eyebrow="Web Application Services" title="Web Application Development" text="We design, build, and modernize web applications that match your business goals and user needs — from customer portals and SaaS platforms to internal tools and enterprise-grade dashboards, built to perform and scale." /><Button>Build your web</Button></div></div></section>
    <section className="e2e-mobile"><div className="site-container e2e-mobile-grid"><div><Heading eyebrow="FAQ" title={<>Mobile App<br />Development</>} text="From first concept to App Store and Play Store submission, we handle the full mobile development lifecycle — design, engineering, backend integration, and long-term maintenance — for native iOS, native Android, and cross-platform builds." /><Button>Build your mobile app</Button></div><div className="e2e-accordion">{["Native iOS", "Native Android", "Cross-Platform", "Backend & Integration"].map((item) => <button type="button" key={item}>{item}</button>)}</div></div></section>
    <section className="e2e-pink e2e-saas"><div className="site-container"><Heading center eyebrow="SAAS Product Services" title="SaaS Product Development" text="We help startups and growing businesses design, develop, launch, and improve modern SaaS products — for web platforms, B2B software, customer portals, internal tools, and subscription-based digital businesses." /><div className="e2e-centered-button"><Button>Build your SAAS product</Button></div><div className="e2e-saas-grid"><article className="e2e-saas-strategy"><small>Strategy</small><h3>Product &amp; Discovery</h3><p>Roadmap, feature priorities, and user flows defined before development starts.</p><img src="/images/end-to-end-figma/raw-16.png" alt="" /></article><div className="e2e-saas-stack"><article><small>Build</small><h3>Multi-Tenant Architecture</h3><p>Subscription billing, role-based access, and infrastructure built to scale.</p></article><article><small>Growth</small><h3>Launch &amp; Iterate</h3><p>Cloud deployment, QA, and ongoing improvement based on real user feedback.</p></article></div><img src="/images/end-to-end-figma/raw-07.jpeg" alt="SaaS product development" /></div></div></section>
    <section className="e2e-split e2e-cloud"><div className="site-container e2e-split-grid"><img src="/images/end-to-end-figma/raw-14.png" alt="Cloud infrastructure" /><div><Heading eyebrow="Cloud & DevOps Services" title="Cloud &amp; DevOps" text="We help startups and growing businesses modernize infrastructure, automate delivery, and improve performance through end-to-end Cloud & DevOps support for SaaS platforms, web apps, mobile backends, and digital products." /><Button>Modernize your infrastructure</Button></div></div></section>
    <section className="e2e-qa"><div className="site-container"><Heading center eyebrow="Test your product before and after release" title="QA &amp; Testing Services" text="We help startups and growing businesses improve product quality through practical QA and testing — for SaaS platforms, web apps, mobile apps, APIs, internal systems, and digital products of every kind." /><div className="e2e-centered-button"><Button>Test your product</Button></div><div className="e2e-qa-grid"><div>{qaRows.map(([title, text], index) => <article key={title}><b>{index + 1}</b><h3>{title}</h3><p>{text}</p></article>)}</div><img src="/images/end-to-end-figma/raw-17.png" alt="QA team testing software" /></div></div></section>
    <section className="e2e-compare"><div className="site-container"><Heading eyebrow="Why us?" title="Why Use Our End to End Development Service?" text="Every stage of your build, handled by one accountable team — here&apos;s how our approach compares service by service." /><div className="e2e-table"><div className="e2e-table-head"><b>Particulars</b><b>Freelancer</b><b>Traditional Agencies</b><b>Byte Innovations</b></div>{compareRows.map((row, index) => <div className="e2e-table-row" key={row}><span>{row}</span><i>{index < 2 ? "✓" : "○"}</i><i>{index === 0 || index === 1 || index === 5 ? "✓" : "○"}</i><i>✓</i></div>)}</div></div></section>
    <section className="e2e-contact"><div className="site-container e2e-contact-grid"><div><Heading eyebrow="Let’s talk" title={<>Let Our Expertise Help<br />Redefine Your Business!</>} text="Empower your business with our expertise and redefine success. Access top-notch developers with years of experience and maximize the full potential of your project development" />{["Expert teams of dedicated software developers with customized strategies", "Our skilled team uses trusted technology for maximum impact", "Implement rigorous protocols on high-security and transparency", "Provide a cost-efficient model that maximizes productivity"].map((item) => <p className="e2e-check" key={item}>✓ <span>{item}</span></p>)}</div><form className="e2e-form"><h3>Let&apos;s connect</h3><div><input aria-label="Name" placeholder="Name" /><input aria-label="Company Name" placeholder="Company Name" /></div><input aria-label="Email" placeholder="Email" /><input aria-label="Phone Number" placeholder="Phone Number" /><textarea aria-label="Message" placeholder="Message" /><button type="button">Send messege</button></form></div></section>
    <section className="e2e-ready"><div className="site-container"><Heading center eyebrow="Contact us" title="Ready to Scale Your Team?" text={<>Whether you&apos;re building a product, expanding your operations, or filling critical skill gaps, Byte Innovations provides the professionals you need—quickly, reliably, and without the complexity of traditional hiring.<br /><br />From recruitment and deployment to payroll, compliance, and ongoing workforce management, we become your trusted workforce partner so your team can stay focused on delivering results.<br /><br /><strong>Let&apos;s build your team—faster, smarter, and with confidence.</strong></>} /><div className="e2e-centered-button"><Button>Let&apos;s Build Together</Button></div><div className="e2e-ready-collage"><div><img src="/images/end-to-end-figma/raw-19.png" alt="Byte Innovations pattern" /><img src="/images/hero-whiteboard.png" alt="Byte Innovations developers" /></div><img src="/images/end-to-end-figma/raw-09.png" alt="Byte Innovations team" /><div><img src="/images/end-to-end-figma/raw-01.png" alt="Byte Innovations office" /><img src="/images/end-to-end-figma/raw-19.png" alt="Byte Innovations pattern" /></div></div></div></section>
  </main>;
}
